/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

/**
 *
 * @author Abel Bima Wiratama
 */
public class PemilihanDokter extends javax.swing.JFrame {

    /**
     * Creates new form PemilihanDokter
     */
    public PemilihanDokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcoDok = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tbNama = new javax.swing.JTextField();
        tbAlamat = new javax.swing.JTextField();
        tbUsia = new javax.swing.JTextField();
        tbJk = new javax.swing.JTextField();
        tbGd = new javax.swing.JTextField();
        tbStatus = new javax.swing.JTextField();
        tbKewa = new javax.swing.JTextField();
        tbwaktu = new javax.swing.JTextField();
        tbdokter = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Pilih Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 90, 90, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Pemilihan Dokter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 40, 130, 20);

        jcoDok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah Satu--", "Dr.Abbas", "Dr.Bejo", "Dr.Ini" }));
        jcoDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcoDokActionPerformed(evt);
            }
        });
        getContentPane().add(jcoDok);
        jcoDok.setBounds(190, 90, 170, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jPanel1.setLayout(null);

        jLabel14.setText("Nama");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 20, 50, 30);

        jLabel15.setText("Alamat");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 50, 50, 30);

        jLabel16.setText("Usia");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 80, 40, 30);

        jLabel17.setText("Jenis Kelamin");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 110, 90, 30);

        jLabel18.setText("Golongan Darah");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 140, 100, 30);

        jLabel19.setText("Status");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 170, 90, 30);

        jLabel20.setText("Kewarganegaraan");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(20, 200, 100, 30);

        jLabel21.setText("Waktu Praktek");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(20, 230, 100, 30);

        jLabel22.setText("Dokter Spesialis");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(20, 260, 100, 30);

        tbNama.setEditable(false);
        jPanel1.add(tbNama);
        tbNama.setBounds(140, 20, 170, 30);

        tbAlamat.setEditable(false);
        jPanel1.add(tbAlamat);
        tbAlamat.setBounds(140, 50, 170, 30);

        tbUsia.setEditable(false);
        jPanel1.add(tbUsia);
        tbUsia.setBounds(140, 80, 170, 30);

        tbJk.setEditable(false);
        tbJk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbJkActionPerformed(evt);
            }
        });
        jPanel1.add(tbJk);
        tbJk.setBounds(140, 110, 170, 30);

        tbGd.setEditable(false);
        jPanel1.add(tbGd);
        tbGd.setBounds(140, 140, 170, 30);

        tbStatus.setEditable(false);
        jPanel1.add(tbStatus);
        tbStatus.setBounds(140, 170, 170, 30);

        tbKewa.setEditable(false);
        tbKewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKewaActionPerformed(evt);
            }
        });
        jPanel1.add(tbKewa);
        tbKewa.setBounds(140, 200, 170, 30);

        tbwaktu.setEditable(false);
        jPanel1.add(tbwaktu);
        tbwaktu.setBounds(140, 230, 170, 30);

        tbdokter.setEditable(false);
        tbdokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbdokterActionPerformed(evt);
            }
        });
        jPanel1.add(tbdokter);
        tbdokter.setBounds(140, 260, 170, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 140, 330, 320);

        setSize(new java.awt.Dimension(476, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbJkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbJkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbJkActionPerformed

    private void tbKewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbKewaActionPerformed

    private void tbdokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbdokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbdokterActionPerformed

    private void jcoDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcoDokActionPerformed
        // TODO add your handling code here:
        if(jcoDok.getSelectedItem().equals("Dr.Abbas")){
            tbNama.setText("Dr.Abbas");
            tbAlamat.setText("Jl.Sinisitu");
            tbUsia.setText("23 Tahun");
            tbJk.setText("Laki-Laki");
            tbGd.setText("A");
            tbStatus.setText("Belum Menikah");
            tbKewa.setText("Abu Dabi");
            tbwaktu.setText("Pagi (5 AM - 4 PM)");
            tbdokter.setText("Dokter Jantung");
        }
        else 
        if(jcoDok.getSelectedItem().equals("Dr.Bejo")){
            tbNama.setText("Dr.Bejo");
            tbAlamat.setText("Jl.AlwaysBejo");
            tbUsia.setText("21 Tahun");
            tbJk.setText("Laki-Laki");
            tbGd.setText("O");
            tbStatus.setText("Belum Menikah");
            tbKewa.setText("Indonesia");
            tbwaktu.setText("Pagi (4 AM - 5 PM)");
            tbdokter.setText("Dokter Umum");
        }
        else 
        if(jcoDok.getSelectedItem().equals("Dr.Ini")){
            tbNama.setText("Dr.Ini Puji Astutik");
            tbAlamat.setText("Jl.Cendana, Papua");
            tbUsia.setText("20 Tahun");
            tbJk.setText("Perempuan");
            tbGd.setText("B");
            tbStatus.setText("Belum Menikah");
            tbKewa.setText("Indonesia");
            tbwaktu.setText("Pagi (7 AM - 3PM)");
            tbdokter.setText("Dokter Kecantikan");
        }
    }//GEN-LAST:event_jcoDokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemilihanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemilihanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemilihanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemilihanDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemilihanDokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcoDok;
    private javax.swing.JTextField tbAlamat;
    private javax.swing.JTextField tbGd;
    private javax.swing.JTextField tbJk;
    private javax.swing.JTextField tbKewa;
    private javax.swing.JTextField tbNama;
    private javax.swing.JTextField tbStatus;
    private javax.swing.JTextField tbUsia;
    private javax.swing.JTextField tbdokter;
    private javax.swing.JTextField tbwaktu;
    // End of variables declaration//GEN-END:variables
}
